package com.jingluo.jingluo.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_status
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String courseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_info
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String courseInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.notice
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;
}