package com.jingluo.jingluo.entity;

import lombok.Data;

@Data
public class Directory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.dir_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer dirId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.base_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.parent_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.dir_title
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String dirTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;
}