package com.jingluo.jingluo.entity;

import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.course_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.class_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer classId;

    //管理员学生code
    private String studentCode;

    //团队头像
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_name
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */

    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_info
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String groupInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.stu_num
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer stuNum;

    //是否发布 0私有 1发布
    private String isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_from
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String createFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;

    private List<Student> student;
}