package com.jingluo.jingluo.entity;

import lombok.Data;

import java.util.Date;

@Data
public class KnowBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.base_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.course_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.group_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.base_name
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String baseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.parent_name
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.base_info
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String baseInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.create_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.update_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.doc_num
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer docNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.read_num
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.att_num
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer attNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.base_kind
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String baseKind;

    //是否在团队首页显示 0否 1是
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.is_public
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.is_delete
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String isDelete;

    //是否是
    private String createFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_base.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;
}