package com.jingluo.jingluo.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Mission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mission_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer missionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.course_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer stageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_title
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String misTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.description
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_leader
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String misLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.create_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.plan_deal_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date planDealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_key
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String misKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.mis_status
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String misStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mission.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;
}