package com.jingluo.jingluo.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Stage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.stage_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer stageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.course_id
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.sta_title
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String staTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.sta_leader
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String staLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.sta_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Integer staTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.description
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.create_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.plan_deal_time
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private Date planDealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.sta_key
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String staKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.sta_status
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String staStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.reserved_1
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.reserved_2
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.reserved_3
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    private String reserved3;
}