package com.jingluo.jingluo.entity;

import lombok.Data;

/**
 * @Description TODO
 * @Author 焦斌
 * @Date 2020/4/8 19:49
 */
@Data
public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Wed Apr 08 21:49:31 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated Wed Apr 08 21:49:31 CST 2020
     */
    private Integer studentId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.group_id
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.is_admin
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_code
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String studentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.head_img
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String headImg;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.nick_name
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.reserved_1
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.reserved_2
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.reserved_3
     *
     * @mbggenerated Wed Apr 08 19:54:01 CST 2020
     */
    private String reserved3;
}
