package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.Directory;

import java.util.List;

public interface DirectoryMapper {

    List<Directory> selectAllFirstDirs(Integer baseId);

    List<Directory> selectAllSecondDirs(Integer dirId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(Directory record);

}