package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.Group;
import com.jingluo.jingluo.entity.Student;
import com.jingluo.jingluo.entity.StudentGroup;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GroupMapper {


    int insertGroupStudent(StudentGroup sg);

    int deleteGroup(Integer groupId);

    int deleteStudentGroup(Integer groupId);

    Group findGroupId(Integer groupId);

    void deleteGroupMember(Integer studentId);

    List<Group> selectGroupByClassId(Integer classId);

    List<Group> selectGroupByGroupName(String selectName);

    Group selectGroupByGroupId(Integer groupId);

    List<Group> selectAllGroupByUserCode(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(Group record);

    List<Group> selectAllGroup();

    List<Student> selectStudentByGroupId(Integer groupId);

    StudentGroup selectStundentGroup(StudentGroup sg);

    //StudentGroupMapper selectStundentGroup(@Param("studentId") Integer studentId,@Param("groupId") Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */


}