package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.Group;
import com.jingluo.jingluo.entity.StudentGroup;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(Group record);

    int insertGroupStudent(StudentGroup sg);

    int deleteGroup(Integer groupId);

    int deleteStudentGroup(Integer groupId);

    Group findGroupId(Integer groupId);

    void deleteGroupMember(Integer studentId);

    List<Group> selectGroupByClassId(Integer classId);

    Group selectGroupByGroupName(String selectName);
}