package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.KnowBase;
public interface KnowBaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(KnowBase record);
}