package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.KnowBase;

import java.util.List;

public interface KnowBaseMapper {

    List<KnowBase> selectKnowBasesByUserCode(String userCode);

    List<KnowBase> selectKnowBasesByGroupId(Integer groupId);

    List<KnowBase> selectKBByUserCodeAndKeyWord(String userCode, String keyWord);

    List<KnowBase> selectKBByGroupIdAndKeyWord(Integer groupId, String keyWord);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(KnowBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_base
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(KnowBase record);
}