package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.KnowDoc;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KnowDocMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_doc
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(KnowDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_doc
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(KnowDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_doc
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(KnowDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_doc
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(KnowDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_doc
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(KnowDoc record);
}