package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.Stage;

public interface StageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insert(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int insertSelective(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKeySelective(Stage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbggenerated Sun Apr 12 14:02:13 CST 2020
     */
    int updateByPrimaryKey(Stage record);
}