package com.jingluo.jingluo.mapper;

import com.jingluo.jingluo.entity.StudentLink;

public interface StudentLinkMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    int insert(StudentLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    int insertSelective(StudentLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    StudentLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    int updateByPrimaryKeySelective(StudentLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_link
     *
     * @mbggenerated Tue May 05 21:51:04 CST 2020
     */
    int updateByPrimaryKey(StudentLink record);
}